# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76d2f504a52cb3818a3173512611b4bcae77d7e57ff7c342a7e3447f7131f5dd06ac54f47bd351130331d592d14c0dcd70e8633a27101cb39846f077bc41ba75

test:
  secret_key_base: 749e31e8146478b3c0a3002ac9075356631a94686ffb3472b18d1e2af3f4892618b0346789fe5f3a6ad6dce3f5485feb99c5b0a137373fe82204a25d4e26a24d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
